app/mod_school/views.py
from flask import Blueprint, g, render_template, flash, redirect, request, url_for, abort
from flask.ext.login import login_required, login_user, logout_user, current_user
from flask.ext.babel import gettext as _

from .models import School
from .forms import SchoolForm

schools = Blueprint('schools', __name__)

@schools.route('/', methods=['GET'])
def home():
    from app.mod_event import Event
    from app.mod_proposal import Proposal

    if g.is_default_school:
        events = Event.objects.filter().order_by('-start')
    else:
        events = Event.objects.filter(schools=g.school).order_by('-start')

    if g.is_default_school:
        proposals = Proposal.objects.filter(published=True).order_by('-created')
    else:
        proposals = Proposal.objects.filter(schools=g.school, published=True).order_by('-created')

    return render_template('school/home.html', school=g.school, events=events, proposals=proposals, current_user=current_user)

@schools.route('/schools/add', methods=['GET', 'POST'])
def add_school():
    if not current_user.is_admin():
        abort(403)
    
    form = SchoolForm()
    if form.validate_on_submit():		
        s = School()
        form.populate_obj(s)
        s.save()
        return redirect(url_for('schools.add_school'))
    return render_template('school/add_school.html', form=form)

app/templates/macros/_form.html
{% macro render_checkbox(field) %}
<div class="checkbox{% if field.errors %} has-error{% endif %}">
    <label for="{{ field.id }}">
        {{ field }}{{ field.label.text }}
    </label>
    <span class="help-inline">{{ field.description }}</span>
    {% if field.errors -%}
    <ul class="help-block">
        {% for error in field.errors -%}
        <li>{{ error|e }}</li>
        {%- endfor %}
    </ul>
    {%- endif %}
</div>
{% endmacro%}


{% macro render_radio(field) %}
<div class="form-group{% if field.errors %} has-error{% endif %}">
    {{ field.label(class_="control-label") }}
    <div class="">
        {% for subfield in field -%}
        <label for="{{ subfield.id }}" class="radio-inline">
            {{ subfield }} {{ subfield.label.text }}
        </label>
        {%- endfor %}
        <span class="help-inline">{{ field.description }}</span>
        {% if field.errors -%}
        <ul class="help-block">
            {% for error in field.errors -%}
            <li>{{ error }}</li>
            {%- endfor %}
        </ul>
        {%- endif %}
    </div>
</div>
{% endmacro %}


{% macro render_datepicker(field) %}
<div class="form-group{% if field.errors %} has-error{% endif %}">
    <label class="control-label" 
        for="{{ field.id }}">
        {{ field.label }}
    </label>
    <div class='input-group date'>
        {{ field(class='form-control') }}
        <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
        </span>
        <span class="help-inline">{{ field.description }}</span>
        {% if field.errors -%}
        <ul class="help-block">
            {% for error in field.errors -%}
            <li>{{ error }}</li>
            {%- endfor %}
        </ul>
        {%- endif %}
    </div>
</div>
{% endmacro %}


{% macro render_textarea(field) %}
<div class="form-group{% if field.errors %} has-error{% endif %}">
    <label class="control-label" 
        for="{{ field.id }}">
        {{ field.label }}
    </label>
    <div class="">
        {{ field(class_="form-control", rows="4") }}
        <span class="help-inline">{{ field.description }}</span>
        {% if field.errors -%}
        <ul class="help-block">
            {% for error in field.errors -%}
            <li>{{ error }}</li>
            {%- endfor %}
        </ul>
        {%- endif %}
    </div>
</div>
{% endmacro %}


{% macro render_file(field) %}
<div class="form-group{% if field.errors %} has-error{% endif %}">
    <label class="control-label" 
        for="{{ field.id }}">
        {{ field.label }}
    </label>
    <div class="">
        {{ field }}
        <span class="help-inline">{{ field.description }}</span>
        {% if field.errors -%}
        <ul class="help-block">
            {% for error in field.errors -%}
            <li>{{ error }}</li>
            {%- endfor %}
        </ul>
        {%- endif %}
    </div>
</div>
{% endmacro %}


{% macro render_input(field) %}
<div class="form-group{% if field.errors %} has-error{% endif %}">
    <label class="control-label" 
        for="{{ field.id }}">
        {{ field.label }}
    </label>
    <div class="">
        {{ field(class_="form-control") }}
        <span class="help-inline">{{ field.description }}</span>
        {% if field.errors -%}
        <ul class="help-block">
            {% for error in field.errors -%}
            <span class="help-block error">{{ error }}</span>
            {%- endfor %}
        </ul>
        {%- endif %}
    </div>
</div>
{% endmacro %}


{% macro render_action(field) %}
<div class="form-group">
    <div class="form-actions">
        {{ field(class_="btn btn-primary") }}
    </div>
</div>
{% endmacro %}


{% macro render_form(url, form, horizontal=False, legend=None, confirm_msg=None, formid=None) %}
{% set idattr = "id=" + formid if formid else "" %}
<form {{idattr}} class="{% if horizontal %}form-horizontal{% endif %}" method="POST" action="{{ url }}"
    {% if confirm_msg %}onsubmit='return confirm("{{ confirm_msg }}");' {% endif %} 
    {% if form.multipart %}enctype="multipart/form-data"{% endif %} >
    {{ form.hidden_tag() }}
        {% if legend %}
        <legend>{{ legend|safe }}</legend>
        {% endif %}
        {% set focus = True %}
        {% for field in form %}
            {% if field.type != "HiddenField" and field.type != "CSRFTokenField" %}
                {% if field.type == "RadioField" %}
                    {{ render_radio(field) }}
                {% elif field.type == "BooleanField" %}
                    {{ render_checkbox(field) }}
                {% elif field.type == "SubmitField" %}
                    {{ render_action(field) }}
                {% elif field.type == "TextAreaField" %}
                    {{ render_textarea(field) }}
                {% elif field.type == "DateField" or field.type == "DateTimeField" %}
                    {{ render_datepicker(field) }}
                {% elif field.type == "FileField" %}
                    {{ render_file(field) }}
                {% elif field.type == "TextField" %}
                    {% if focus %}
                        {{ render_input(field) }}
                        {% set focus = False %}
                    {% else %}
                        {{ render_input(field) }}
                    {% endif %}
                {% else %}
                    {{ render_input(field) }}
                {% endif %}
            {% endif %}
        {% endfor %}
</form>
{% endmacro %}

app/templates/macros/_interest.html
{% macro interested_counter(obj, type) %}
<div class="interested interested-counter" obj-id="{{ obj.id }}" obj-type="{{ type }}">
    <!-- Commenting this out for now. Do we need to display the number interested when it's already in the page information?-->
	<!--<div class="counter"></div>-->
	{% if obj.user_is_interested(current_user) %}    
    <div class="add" style="padding-left: 0px; margin-bottom: 10px;">add me</div>
    <div class="remove button">remove me</div>
    {% else %}
    <div class="add button">add me</div>
    <div class="remove">remove me</div>
    {% endif %}
</div>
{% endmacro %}



{% macro interested_check(obj, type='proposal', current_user) %}
{% if not current_user.is_anonymous() %}
<div class="interested interested-checker interested-status col-md-1" obj-id="{{ obj.id }}" obj-type="{{ type }}" style="padding-left:0px; margin-top:15px;width:35px;">
	{% if obj.user_is_interested(current_user) %}	
    <span class="remove button glyphicon glyphicon-ok" style="font-size: 20px;"></span>
	{% else %}
	<span class="add button glyphicon glyphicon-ok" style="font-size: 20px;"></span>
	{% endif %}
</div>
{% endif %}
{% endmacro %}

app/templates/macros/_nav.html
{% macro schools_nav_dropdown() %}
{% if g.all_schools.count()>1 %}
<li>
	<div class="btn-group">
	  <button type="button" class="btn"><a href="{{ url_for('schools.home') }}">/ {{ g.school.name }}</a></button>
	  <button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
	    <span class="caret"></span>
	    <span class="sr-only">Toggle Dropdown</span>
	  </button>
	  <ul class="dropdown-menu" role="menu">
	    {% for school in g.all_schools %}
	    {% if school!=g.default_school %}
	    <li><a href="{{ url_for_school('schools.home', school=school) }}">/ {{ school.name }}</a></li>
	    {% endif %}
	    {% endfor %}
	  </ul>
	</div>
</li>
{% endif %}
{% endmacro %}